CREATE TABLE workers(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    qualification VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    examdate DATE
)